model:
  name: MyAIModel
  version: 1.0
  architecture: 
    type: neural_network
    layers:
      - type: convolutional
        filters: 32
        kernel_size: 3
        activation: relu
      - type: max_pooling
        pool_size: 2
      - type: flatten
      - type: dense
        units: 128
        activation: relu
      - type: output
        units: 10
        activation: softmax

training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam
  loss_function: categorical_crossentropy

data:
  input_shape: [28, 28, 1]
  num_classes: 10
  augmentation:
    rotation_range: 10
    width_shift_range: 0.1
    height_shift_range: 0.1
    shear_range: 0.1
    zoom_range: 0.1
    horizontal_flip: false
    fill_mode: nearest

logging:
  log_dir: ./logs
  log_level: info