name: Model Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Use GPU runner for model testing
    runs-on: ubuntu-latest-4-32gb-nvidia

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check GPU availability
        run: |
          python -c "import torch; print('CUDA available:', torch.cuda.is_available())"

      - name: Run model manager
        run: |
          python src/model_manager.py

      - name: Run workflow
        run: |
          python src/workflow.py

      #- name: Run tests
      #  run: |
      #    pytest tests/test_training.py
      #    pytest tests/test_preprocessing.py
      #    pytest tests/test_inference.py

      #- name: Validate model performance
      #  run: |
      #    python src/evaluation/metrics.py